version: 0.2

phases:
  install:
    commands:
      - echo "Installing Java 21..."
      - yum remove -y java-17-amazon-corretto-headless || true
      - yum install -y java-21-amazon-corretto-devel
      - export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - mvn -version

  pre_build:
    commands:
      - echo "Entering config-server module..."
      - cd platform/config-server     # IMPORTANT: Correct folder
      - echo "Running Maven build..."
      - mvn clean install
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - REPOSITORY_URI=269825205626.dkr.ecr.ap-south-1.amazonaws.com/configserver_app
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - export REPOSITORY_URI IMAGE_TAG

  build:
    commands:
      - echo "Build started on `date`"
      - cd platform/config-server
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on `date`"
      - cd platform/config-server
      - echo "Pushing Docker images to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Generating imagedefinitions.json..."
      - DOCKER_CONTAINER_NAME=configserver_app
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME
