version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - echo "===== INSTALL PHASE ====="
      - echo "PWD (repo root) =>"
      - pwd
      - echo "Listing repo root =>"
      - ls
      - echo "Checking ecommerce_backend folder =>"
      - ls ecommerce_backend
      - echo "Installing Java 21..."
      - yum remove -y java-17-amazon-corretto-headless || true
      - yum install -y java-21-amazon-corretto-devel
      - export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - mvn -version

  pre_build:
    commands:
      - echo "===== PRE_BUILD PHASE ====="
      - cd ecommerce_backend/platform/api-gateway
      - echo "Now in:"
      - pwd
      - echo "Running Maven build..."
      - mvn clean package -DskipTests
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - REPOSITORY_URI=269825205626.dkr.ecr.ap-south-1.amazonaws.com/apigateway_server
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - export REPOSITORY_URI IMAGE_TAG

  build:
    commands:
      - echo "===== BUILD PHASE ====="
      - echo "Building Docker image..."
      - ls -R
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "===== POST_BUILD PHASE ====="
      - echo "Pushing Docker images..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Generating imagedefinitions.json..."
      - DOCKER_CONTAINER_NAME=apigateway_server
      - printf '[{"name":"%s","imageUri":"%s"}]' "$DOCKER_CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
      - echo "imagedefinitions.json:"
      - cat imagedefinitions.json
      - cp imagedefinitions.json "$CODEBUILD_SRC_DIR"

artifacts:
  files:
    - imagedefinitions.json
    - ecommerce_backend/platform/api-gateway/target/api-gateway.jar
